### ISSUE TITLE
Expected dynamic type 'string', but had type 'object'

### ISSUE THREAD

**Issue by zhanguangao** [rusel1989/react-native-bluetooth-serial#14]
When I try to connect device,there will be occurred 'expected dynamic type string, but had type object'.

**Comment by rusel1989** [comment]
@zhanguangao hey, please specify react native version, platform etc...

**Comment by zhanguangao** [comment]
I solve this problem by myselft.Thank you!

**Comment by rusel1989** [comment]
@zhanguangao nice, can you please tell me what was the issue, i would maybe mention it in readme in case someone else experiences it in future

**Comment by zhanguangao** [comment]
I don't know what accurate problem.I code myselft instend of using you example.
