### ISSUE TITLE
New NPM Version

### ISSUE THREAD

**Issue by philberg** [rusel1989/react-native-bluetooth-serial#26]
Could you please publish a new version to NPM?  The addition of `removeListener` is very important to me, and is now in the readme, but the NPM version is 3 months, old.

Thanks!!

**Comment by rusel1989** [comment]
Hey @philberg I will release new version soon, I just have couple fixes i want to finish ... You can remove listeners using  `DeviceEventEmitter.removeListener(eventName, handler)` or if you want latest stuff install from github `npm i -S github:rusel1989/react-native-bluetooth-serial#master` for now
