### ISSUE TITLE
Unable to connect to Android device

### ISSUE THREAD

**Issue by clementino36** [rusel1989/react-native-bluetooth-serial#29]
Hi,

I've cloned the example which works fine. Then I've tryed to connect my Android device to both Android and iOS devices after pairing them. Oddly, i've only been able to connect my Android phone to an iPhone but not to another Android device even though they are all paired.

Has anyone encountered that ?

**Comment by ghost** [comment]
@clementino36  I have a same problem. How can I do this?

**Comment by clems36** [comment]
I haven't worked with the library ever since, can't help you...
