### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by vincenzoiacovone** [rusel1989/react-native-bluetooth-serial#3]
Always no devices found on iOS

Promise.all([
      Bluetooth.isEnabled(),
      Bluetooth.isConnected(),
      Bluetooth.list()
    ])
    .then((values) => {
      console.log(values)
    })

Output: true, false, []

React Native 0.31, iOS 9.3

**Comment by rusel1989** [comment]
On ios you have to add your service UUIDs here ... https://github.com/rusel1989/react-native-bluetooth-serial/blob/master/ios/RCTBluetoothSerial/BLEDefines.h ... and then handle it here https://github.com/rusel1989/react-native-bluetooth-serial/blob/master/ios/RCTBluetoothSerial/BLE.m#L535 ... just send PR with necessary changes i will accept it ... also if you just need to list devices and no read/write maybe look for another lib
