### ISSUE TITLE
A doubt about this tool

### ISSUE THREAD

**Issue by codingwithbatista** [rusel1989/react-native-bluetooth-serial#33]
Does This tool serve to send archives for impression in a thermal printer?

**Comment by rusel1989** [comment]
@costabatista Sorry I dont know what "Send archives for impression" means ? 

Anyway I am using it to print receipts on thermal printers without any difficulties both ios and android.

**Comment by codingwithbatista** [comment]
Sorry about my bad english, I wanna mean "Send stream of bytes to thermal printers". So, later some number of tentatives i did a bluetooth connection using your implementation. Thanks! =)

**Comment by rusel1989** [comment]
:+1: I am glad to hear that, I am closing this issue for now, feel free to reopen if you need some further info ...

**Comment by pewh** [comment]
@rusel1989 would you mind if you inform me (or give a link) about what data need to send to print receipts via thermal printers? My use case is print invoice (also contain image & qr code). Thanks.
