### ISSUE TITLE
Device list always returns empty

### ISSUE THREAD

**Issue by MagganKoolman** [rusel1989/react-native-bluetooth-serial#57]
I must have missed an essential part for this module. Whenever discoverUnpairDevices is called it returns an empty list. No error messages or warnings are thrown. I used the following code.

```
import BluetoothSerial from 'react-native-bluetooth-serial'

BluetoothSerial.enable()
.then((res) => console.log(res))
.catch((err) => console.log(err.message))

BluetoothSerial.discoverUnpairedDevices()
.then((unpairedDevices) => {
  console.log(unpairedDevices)
})
.catch((err) => console.log(err.message))
```

**Comment by natrey** [comment]
I was trying to run the example app on android 6.0 and did also receive an empty list. In my case, i had to add additional config lines to AndroidManifest.xml
```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```
as mentioned [here](https://stackoverflow.com/a/36164455/5899355)

**Comment by joshuapinter** [comment]
More than that, you need to ask for permissions in the Activity as well. The SO answer you referenced shows how to do that.

**Comment by gabrielhpugliese** [comment]
@joshuapinter is it enough doing this before calling `BluetoothSerial.discoverUnpairedDevices()`?
```
    const granted = await PermissionsAndroid.requestMultiple(
      [
        PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
        PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION,
      ],
      {
        'title': 'Permission requested',
        'message': 'Give it',
      }
    );
```

Or should it be implemented on the java part?

EDIT: damn, worked! :D thanks

**Comment by joshuapinter** [comment]
@gabrielhpugliese Nice job and thanks for posting - good for everybody else landing here! 👍
