### ISSUE TITLE
Property 'on'

### ISSUE THREAD

**Issue by gillestasse** [rusel1989/react-native-bluetooth-serial#6]
When I import (after install) :
`import BluetoothSerial from 'react-native-bluetooth-serial'`

I get the following error on the device :
`ExceptionsManager.js:61Cannot set property 'on' of undefined`

**Comment by rusel1989** [comment]
@gillestasse Hey, what version of react-native are you using and, did you link ios and android native code ?

**Comment by gillestasse** [comment]
Hi.

Sorry for the lack of details.

I linked it on Android.

React-native : 

```
react-native-cli: 1.0.0
react-native: 0.33.0
```

**Comment by rusel1989** [comment]
@gillestasse okay that should work without any problem, it seems to me that it is not properly linked ... did you check it is correctly linked in `android/src/main/java/com/appname/MainApplication.java`

... it should look something like this
<img width="636" alt="snimek obrazovky 2016-09-22 v 1 21 40 odp" src="https://cloud.githubusercontent.com/assets/5787069/18746427/947f48fa-80c7-11e6-9adf-6e3b41e71a68.png">

**Comment by gillestasse** [comment]
@rusel1989 Thanks a lot for you fast answer. It works now, i don't have any error message. Did I miss something in the doc ? I tried to do it through the automatic method (rnpm link). When I ran rnpm link a second time it confirmed that the library was already linked. Is it necessary to do the automatic and the manual method ?

**Comment by rusel1989** [comment]
You're welcome. It wasn't your fault, i should update the docs, rnpm is deprecated, it has been moved to react-native core since version 0.27, i will update the docs and close. You can read the more [here](https://github.com/rnpm/rnpm).

**Comment by kranthi1216** [comment]
I too have same issue. how to resolve this issue in iOS?
