### ISSUE TITLE
Can not connect to ble device

### ISSUE THREAD

**Issue by BigPun86** [rusel1989/react-native-bluetooth-serial#8]
Hey there. I am trying to connect to a RN4020 BLE Modul. On ANdroid i always receive following error:

<img width="423" alt="screen shot 2016-10-18 at 11 14 43" src="https://cloud.githubusercontent.com/assets/7880624/19471593/3971a7de-9524-11e6-9640-f9bb0faf38d9.png">

Any ideas on this?

**Comment by rusel1989** [comment]
Hey BLE is not supported on android ... so that is probably it ... there is currently no plan to support it... so i am closing for now ... any pull request will be welcomed
