### ISSUE TITLE
Scan not finding devices in iOS

### ISSUE THREAD

**Issue by jqn** [rusel1989/react-native-bluetooth-serial#81]
Anyone had any luck finding devices during the scan in iOS with this library?

**Comment by oussama-ahmed** [comment]
Hello, did you find a solution for this problem ?

**Comment by jqn** [comment]
@oussaamaa  I removed the bluetooth feature from my app, at the time I couldn't find a good bluetooth library for react native

**Comment by oussama-ahmed** [comment]
okay .. And now could you recommend me a bluetooth library ?

**Comment by jqn** [comment]
@oussaamaa I haven't had the need for one.

**Comment by oussama-ahmed** [comment]
@jqn The reason is here
https://github.com/nuttawutmalee/react-native-bluetooth-serial-next/issues/11

**Comment by jqn** [comment]
@oussaamaa thanks a lot for sharing

**Comment by fabio-C** [comment]
@oussaamaa  @jqn 
Does this library works with IOS?
