### ISSUE TITLE
Pdf files,

### ISSUE THREAD

**Issue by ibrahimsenan** [rusel1989/react-native-bluetooth-serial#83]
Can we print pdf files to a thermal printer using bluetooth-serial?

**Comment by Uzlopak** [comment]
Obviously not. What you want is BPP and not SPP.

You should learn first about the different BT-Profiles. 
https://en.wikipedia.org/wiki/List_of_Bluetooth_profiles

**Comment by ibrahimsenan** [comment]
Thank you @arasabbasi
